apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2  # Número de réplicas
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: flask-app
          image: srjm2024/backend-jm:2.0
          env:
            - name: FLASK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: FLASK_DB_HOST
              value: db
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"  
              cpu: "250m"       
            limits:
              memory: "256Mi"  
              cpu: "500m"      