apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: srjm2024/frontend-jm:2.0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"  
              cpu: "250m"      
            limits:
              memory: "256Mi"   
              cpu: "500m"    